recipe: default.v1

assistant_id: crazy-climate-professor

language: en

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "RegexFeaturizer"
  - name: "EntitySynonymMapper"
  - name: CountVectorsFeaturizer
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: CountVectorsFeaturizer
    analyzer: "char"
    min_ngram: 3
    max_ngram: 5
  - name: "DIETClassifier"
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1


policies:
  - name: AugmentedMemoizationPolicy
    max_history: 2
  - name: TEDPolicy
    max_history: 10
    max_training_samples: 300
    epochs: 200
    batch_size: 50
  - name: RulePolicy
  - name: MemoizationPolicy
    max_history: 10
